//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoolagScanner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoolagScanner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cdc009 {
            get {
                object obj = ResourceManager.GetObject("Cdc009", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cdc2 {
            get {
                object obj = ResourceManager.GetObject("cdc2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cdc2d {
            get {
                object obj = ResourceManager.GetObject("cdc2d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eraser {
            get {
                object obj = ResourceManager.GetObject("eraser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap greenball {
            get {
                object obj = ResourceManager.GetObject("greenball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap greyball {
            get {
                object obj = ResourceManager.GetObject("greyball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gscan_sm {
            get {
                object obj = ResourceManager.GetObject("gscan-sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gscansplashd {
            get {
                object obj = ResourceManager.GetObject("gscansplashd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        internal static string RES_BLOCKED {
            get {
                return ResourceManager.GetString("RES_BLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling....
        /// </summary>
        internal static string RES_CANCEL {
            get {
                return ResourceManager.GetString("RES_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string RES_CANCELSCAN {
            get {
                return ResourceManager.GetString("RES_CANCELSCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dorks.
        /// </summary>
        internal static string RES_DORKS {
            get {
                return ResourceManager.GetString("RES_DORKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dorks loaded.
        /// </summary>
        internal static string RES_DORKS_LOADED {
            get {
                return ResourceManager.GetString("RES_DORKS_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your own host to scan first..
        /// </summary>
        internal static string RES_E_ENTERHOST {
            get {
                return ResourceManager.GetString("RES_E_ENTERHOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        internal static string RES_E_GENERIC {
            get {
                return ResourceManager.GetString("RES_E_GENERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open file.
        /// </summary>
        internal static string RES_E_OPENFILE {
            get {
                return ResourceManager.GetString("RES_E_OPENFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error occurred while scanning..
        /// </summary>
        internal static string RES_E_SCANERROR {
            get {
                return ResourceManager.GetString("RES_E_SCANERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one dork from the list..
        /// </summary>
        internal static string RES_E_SELECTDORK {
            get {
                return ResourceManager.GetString("RES_E_SELECTDORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your XML-file seems to be incorrect and was not loaded..
        /// </summary>
        internal static string RES_E_XMLINCORRECT {
            get {
                return ResourceManager.GetString("RES_E_XMLINCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string RES_FAILED {
            get {
                return ResourceManager.GetString("RES_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Scan Warning.
        /// </summary>
        internal static string RES_LARGSCAN {
            get {
                return ResourceManager.GetString("RES_LARGSCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean.
        /// </summary>
        internal static string RES_NORESULT {
            get {
                return ResourceManager.GetString("RES_NORESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        internal static string RES_READY {
            get {
                return ResourceManager.GetString("RES_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string RES_SCAN {
            get {
                return ResourceManager.GetString("RES_SCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning.
        /// </summary>
        internal static string RES_SCANNING {
            get {
                return ResourceManager.GetString("RES_SCANNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string RES_SUCCESS {
            get {
                return ResourceManager.GetString("RES_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No warnings.
        /// </summary>
        internal static string RES_VERBOSE0 {
            get {
                return ResourceManager.GetString("RES_VERBOSE0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All warnings.
        /// </summary>
        internal static string RES_VERBOSE1 {
            get {
                return ResourceManager.GetString("RES_VERBOSE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to scan {0} dorks, which may lead to your IP being blocked. Continue?.
        /// </summary>
        internal static string RES_W_LARGESCAN {
            get {
                return ResourceManager.GetString("RES_W_LARGESCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap throbber {
            get {
                object obj = ResourceManager.GetObject("throbber", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
